# Generated by Django 3.0.5 on 2020-04-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.DecimalField(decimal_places=0, max_digits=7)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('players', models.DecimalField(decimal_places=0, max_digits=2)),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
                ('pub_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('category', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
    ]
