# Generated by Django 3.0.5 on 2020-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0002_auto_20200420_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='age',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='No description yet, sorry :)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_players',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_year',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
