# Generated by Django 3.0.5 on 2020-04-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0003_auto_20200421_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='publisher',
            new_name='manufacturer',
        ),
    ]
