# Generated by Django 3.0.5 on 2020-04-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0004_auto_20200421_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='manufacturer',
            field=models.CharField(default='UnknowS', max_length=100),
        ),
    ]
